In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences

sent=['the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define vacabulary size

voc_size=10000


In [6]:
## one hot representation of every words

one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[5678, 7702, 9511, 554],
 [5678, 7702, 9511, 5457],
 [5678, 3631, 9511, 3946],
 [8967, 3680, 5732, 5665, 222],
 [8967, 3680, 5732, 5665, 9553],
 [3553, 5678, 2128, 9511, 1324],
 [9778, 7908, 7594, 5665]]

In [8]:
## word en=mbedding representation

from tensorflow.keras.layers import Embedding
##from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:

sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5678 7702 9511  554]
 [   0    0    0    0 5678 7702 9511 5457]
 [   0    0    0    0 5678 3631 9511 3946]
 [   0    0    0 8967 3680 5732 5665  222]
 [   0    0    0 8967 3680 5732 5665 9553]
 [   0    0    0 3553 5678 2128 9511 1324]
 [   0    0    0    0 9778 7908 7594 5665]]


In [11]:
## feature representation

dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')

In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


array([[[ 0.01098231,  0.0008992 , -0.04739596,  0.04388391,
         -0.03539473, -0.01216913, -0.02071599,  0.04291454,
         -0.00600835,  0.01883383],
        [ 0.01098231,  0.0008992 , -0.04739596,  0.04388391,
         -0.03539473, -0.01216913, -0.02071599,  0.04291454,
         -0.00600835,  0.01883383],
        [ 0.01098231,  0.0008992 , -0.04739596,  0.04388391,
         -0.03539473, -0.01216913, -0.02071599,  0.04291454,
         -0.00600835,  0.01883383],
        [ 0.01098231,  0.0008992 , -0.04739596,  0.04388391,
         -0.03539473, -0.01216913, -0.02071599,  0.04291454,
         -0.00600835,  0.01883383],
        [ 0.01177608, -0.03543273, -0.00414665,  0.03735084,
          0.01763901, -0.0163842 ,  0.04824538,  0.02625766,
          0.04062578, -0.03396086],
        [ 0.01905762,  0.00718609, -0.00043535,  0.03004707,
         -0.01904253,  0.00626743,  0.00029076,  0.00965115,
          0.03697786,  0.03373397],
        [ 0.02022033, -0.02432698,  0.03833633, -0.0